#
#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

[general]
live_config_reload = true

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.cursor]
cursor = '#c8d3f5'
text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono NF"

# NOTE: helpful hex codes
# \x1b = escape (useful for vim-related keybindings)
# \x02 = control-b (the default tmux prefix)

# reload tmux config
[[keyboard.bindings]]
chars = "\u0002r"
key = "R"
mods = "Command"

# update plugins for tmux
[[keyboard.bindings]]
chars = "\u0002U"
key = "U"
mods = "Command"

# install plugins for tmux
[[keyboard.bindings]]
chars = "\u0002I"
key = "I"
mods = "Command"

# split tmux window vertically
[[keyboard.bindings]]
chars = "\u0002|"
key = "E"
mods = "Command"

# split tmux window horizontally
[[keyboard.bindings]]
chars = "\u0002-"
key = "E"
mods = "Command|Shift"

# start tmux search mode
[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command"

# open git manager 'jesseduffield/lazydocker'
[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

# open git manager 'jesseduffield/lazygit'
[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

# open htop
[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Command"

# open interactive tmux session client
[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

# switch to the last tmux session
[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

# open URL
[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

# Save Nvim buffer
[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

# create tmux window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# kill the current pane
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# toggle zoom state of the current tmux pane
[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

# navigate back in vim (ctrl+o)
[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

# navigate forward in vim (ctrl+i)
[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

# enter the tmux command prompt
[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[mouse]
# hide the cursor when typing
hide_when_typing = true
# save selected text to system clipboard
# save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9
# window decoarations
# - full: borders and title bar
# - none: neither borders nor title bar
# - (macos) transparent: title bar, transparent background, and title bar buttons
# - (macos) buttonless: title bar transparent background, but no title bar buttons
decorations = "buttonless"
# spread additional padding evenly around the terminal content
dynamic_padding = true
# dynamically set the window title
dynamic_title = true
# Startup mode
# - Windowed
# - Maximized
# - Fullscreen
# - SimpleFullscreen (macos only)
startup_mode = "SimpleFullscreen"

[window.padding]
x = 2
y = 2
