#
#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

live_config_reload: true

env:
  TERM: xterm-256color

font:
  normal:
    family: "InconsolataGo Nerd Font"
  size: 14.0

window:
  padding:
    x: 2
    y: 2
  # spread additional padding evenly around the terminal content
  dynamic_padding: true
  # window decoarations
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - (macos) transparent: title bar, transparent background, and title bar buttons
  # - (macos) buttonless: title bar transparent background, but no title bar buttons
  decorations: full 
  # dynamically set the window title
  dynamic_title: true
  # Startup mode
  # - Windowed
  # - Maximized
  # - Fullscreen
  # - SimpleFullscreen (macos only)
  startup_mode: Fullscreen
scrolling:
  history: 10000
  multiplier: 3

mouse:
  # hide the cursor when typing
  hide_when_typing: true
  # save selected text to system clipboard
  save_to_clipboard: true

# NOTE: helpful hex codes
# \x1b = escape (useful for vim-related keybindings)
# \x02 = control-b (the default tmux prefix)

key_bindings:
  - { key: R, mods: Command, chars: "\x02r" } # reload tmux config 
  - { key: I, mods: Command, chars: "\x02I" } # install plugins for tmux 
  - { key: E, mods: Command, chars: "\x02|" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x02-" } # split tmux window horizontally
  - { key: F, mods: Command, chars: "lf\n" } # open file manager 'gokcehan/lf'
  - { key: F, mods: Command|Shift, chars: "\x02\x5b\x2f" } # start tmux search mode
  - { key: D, mods: Command, chars: "\x02d" } # open git manager 'jesseduffield/lazydocker'
  - { key: G, mods: Command, chars: "\x02g" } # open git manager 'jesseduffield/lazygit'
  - { key: J, mods: Command, chars: "\x02\x54" } # open t - tmux smart session manager
  - { key: K, mods: Command, chars: "\x02s" } # open interactive tmux session client
  - { key: L, mods: Command, chars: "\x02L" } # switch to the last tmux session
  - { key: O, mods: Command, chars: "\x02u" } # open URL
  - { key: P, mods: Command, chars: ":GoToFile\n" } # files
  - { key: P, mods: Command|Shift, chars: ":GoToCommand\n" } # commands
  - { key: Q, mods: Command, chars: ":q\n" } # quit vim
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # save vim buffer
  - { key: T, mods: Command, chars: "\x02c" } # create a new tmux window
  - { key: W, mods: Command, chars: "\x02x" } # kill the current pane
  - { key: Z, mods: Command, chars: "\x02z" } # toggle zoom state of the current tmux pane
  - { key: Tab, mods: Control, chars: "\x02n" } # switch to next tmux window
  - { key: Grave, mods: Control, chars: "\x02p" } # switch to previous tmux window
  - { key: Comma, mods: Command, chars: "\x02," } # rename the current tmux window
  - { key: LBracket, mods: Command, chars: "\x0f" } # navigate back in vim (ctrl+o)
  - { key: LBracket, mods: Command|Shift, chars: "\x02p" } # switch to next tmux window
  - { key: RBracket, mods: Command, chars: "\x09" } # navigate forward in vim (ctrl+i)
  - { key: RBracket, mods: Command|Shift, chars: "\x02n" } # switch to previous tmux window
  - { key: Semicolon, mods: Command, chars: "\x02:" } # enter the tmux command prompt
  - { key: Key1, mods: Command, chars: "\x021" } # select tmux window 1
  - { key: Key2, mods: Command, chars: "\x022" } #                ... 2
  - { key: Key3, mods: Command, chars: "\x023" } #                ... 3
  - { key: Key4, mods: Command, chars: "\x024" } #                ... 4
  - { key: Key5, mods: Command, chars: "\x025" } #                ... 5
  - { key: Key6, mods: Command, chars: "\x026" } #                ... 6
  - { key: Key7, mods: Command, chars: "\x027" } #                ... 7
  - { key: Key8, mods: Command, chars: "\x028" } #                ... 8
  - { key: Key9, mods: Command, chars: "\x029" } #                ... 9

