#
#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

live_config_reload = true

# NOTE: this is coming from https://github.com/alacritty/alacritty-theme
# We are using tokyo night, obviously
[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono NF"

# NOTE: helpful hex codes
# \x1b = escape (useful for vim-related keybindings)
# \x02 = control-b (the default tmux prefix)

# reload tmux config 
[[keyboard.bindings]]
chars = "\u0002r"
key = "R"
mods = "Command"

# install plugins for tmux 
[[keyboard.bindings]]
chars = "\u0002I"
key = "I"
mods = "Command"

# split tmux window vertically
[[keyboard.bindings]]
chars = "\u0002|"
key = "E"
mods = "Command"

# split tmux window horizontally
[[keyboard.bindings]]
chars = "\u0002-"
key = "E"
mods = "Command|Shift"

# open file manager 'gokcehan/lf'
[[keyboard.bindings]]
chars = """
lf
"""
key = "F"
mods = "Command"

 # start tmux search mode
[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

# open git manager 'jesseduffield/lazydocker'
[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

# open git manager 'jesseduffield/lazygit'
[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

# open htop
[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Command"

# open t - tmux smart session manager
[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

# open interactive tmux session client
[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

# switch to the last tmux session
[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

# open URL
[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

# Commands
[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

# Quit nvim
[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

# Save Nvim buffer
[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

# create tmux window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# kill the current pane
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# toggle zoom state of the current tmux pane
[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

# switch to next tmux window
[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

# navigate back in vim (ctrl+o)
[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

# switch to next tmux window
[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

# navigate forward in vim (ctrl+i)
[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

# switch to previous tmux window
[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

# enter the tmux command prompt
[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[mouse]
  # hide the cursor when typing
hide_when_typing = true
# save selected text to system clipboard
# save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[window]
  # window decoarations
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - (macos) transparent: title bar, transparent background, and title bar buttons
  # - (macos) buttonless: title bar transparent background, but no title bar buttons
decorations = "full"
  # spread additional padding evenly around the terminal content
dynamic_padding = true
  # dynamically set the window title
dynamic_title = true
  # Startup mode
  # - Windowed
  # - Maximized
  # - Fullscreen
  # - SimpleFullscreen (macos only)
startup_mode = "Fullscreen"

[window.padding]
x = 2
y = 2
